{{- if .Values.serviceAccount.create | default false }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flask-chart.serviceAccountName" . }}
  labels:
    {{- include "flask-chart.labels" . | nindent 4 }}
{{- end }}
