replicaCount: 2
image:
  repository: kimjaeyoung98/flask-app
  tag: release-20250626-114131
  pullPolicy: Always
env:
  DB_HOST: mysql-prod.prod.svc.cluster.local
  DB_PORT: '3306'
  DB_USER: produser
  DB_PASSWORD: prodpass
  DB_NAME: ProdDB
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: flask-prod.local
      paths:
        - path: /
          pathType: ImplementationSpecific
service:
  type: NodePort
  port: 80
  targetPort: 5000
serviceAccount:
  create: true
  name: ''
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
