replicaCount: 2

image:
  repository: kimjaeyoung98/flask-app
  tag: prod
  pullPolicy: Always

env:
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_USER: root
  DB_PASSWORD: dev-secret
  DB_NAME: LocalTest

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: flask-prod.local
      paths:
        - path: /
          pathType: ImplementationSpecific


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort  # 외부 접근 위해 변경
  port: 80
  targetPort: 5000

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: 5000  # 명확히 지정

readinessProbe:
  httpGet:
    path: /
    port: 5000  # 명확히 지정

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}
