replicaCount: 1

image:
  repository: flask-app
  tag: latest
  pullPolicy: Never  # 로컬 테스트 시에는 Never로 설정

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort  # 외부 접근 위해 변경
  port: 80
  targetPort: 5000

env: 
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_USER: root
  DB_PASSWORD: root
  DB_NAME: LocalTest

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: 127.0.0.1.nip.io  # 또는 flask.localhost.me 처럼 public nip.io 사용
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: 5000  # 명확히 지정

readinessProbe:
  httpGet:
    path: /
    port: 5000  # 명확히 지정

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}
