replicaCount: 1

image:
  repository: kimjaeyoung98/flask-app
  tag: stage
  pullPolicy: Always

env:
  DB_HOST: mysql-stage.stage.svc.cluster.local
  DB_PORT: "3306"
  DB_USER: stageuser
  DB_PASSWORD: stagepass
  DB_NAME: StageDB

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: flask-stage.local
      paths:
        - path: /
          pathType: ImplementationSpecific

service:
  type: NodePort
  port: 80
  targetPort: 5000

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
