name: Helm CI/CD

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: kimjaeyoung98/flask-app

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:latest

    - name: Set up Kubeconfig
      shell: powershell
      run: |
        if (-Not (Test-Path "$env:USERPROFILE\.kube")) {
        New-Item -ItemType Directory -Path "$env:USERPROFILE\.kube" | Out-Null
        }
        [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("${{ secrets.KUBECONFIG_DATA }}")) | Set-Content "$env:USERPROFILE\.kube\config"


    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.13.0

    - name: Deploy with Helm
      run: |
        helm upgrade --install flask-app ./helm/flask-chart -n default --create-namespace \
          --set image.repository=${{ env.IMAGE_NAME }} \
          --set image.tag=latest
