name: Helm CI/CD with Tag-Based Rollout ver. Unix 2

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: kimjaeyoung98/flask-app

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Remove previous builder (if exists)
      run: docker buildx rm mybuilder || true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        name: mybuilder
        use: true

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate unique release tag
      run: echo "HELM_RELEASE_TAG=release-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:latest
          ${{ env.IMAGE_NAME }}:${{ env.HELM_RELEASE_TAG }}
        no-cache: true

    - name: Set up Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Deploy with Helm using release tag
      run: |
        helm upgrade --install flask-app ./flask-chart -n default --create-namespace \
          --set image.repository=${{ env.IMAGE_NAME }} \
          --set image.tag=${{ env.HELM_RELEASE_TAG }} \
          --set image.pullPolicy=Always
